package stats

import (
	"fmt"
	"sort"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/decline-llc/netsentry/pkg/model"
)

var defaultSeverities = []model.Severity{
	model.SeverityLow,
	model.SeverityMedium,
	model.SeverityHigh,
	model.SeverityCritical,
}

// Stats holds process-local counters exported through /api/metrics.
type Stats struct {
	framesTotal      atomic.Uint64
	controlFrames    atomic.Uint64
	packetsReceived  atomic.Uint64
	packetsProcessed atomic.Uint64
	decodeErrors     atomic.Uint64
	alertsGenerated  atomic.Uint64
	matchCount       atomic.Uint64
	matchDurationNS  atomic.Uint64
	workerPanics     atomic.Uint64
	alertWriteErrors atomic.Uint64

	mu               sync.RWMutex
	alertsBySeverity map[model.Severity]uint64
}

// New creates a Stats instance with stable severity labels preinitialized.
func New() *Stats {
	s := &Stats{alertsBySeverity: make(map[model.Severity]uint64)}
	for _, sev := range defaultSeverities {
		s.alertsBySeverity[sev] = 0
	}
	return s
}

func (s *Stats) IncFrame() {
	if s != nil {
		s.framesTotal.Add(1)
	}
}

func (s *Stats) IncControlFrame() {
	if s != nil {
		s.controlFrames.Add(1)
	}
}

func (s *Stats) IncPacketReceived() {
	if s != nil {
		s.packetsReceived.Add(1)
	}
}

func (s *Stats) IncPacketProcessed() {
	if s != nil {
		s.packetsProcessed.Add(1)
	}
}

func (s *Stats) IncDecodeError() {
	if s != nil {
		s.decodeErrors.Add(1)
	}
}

func (s *Stats) IncWorkerPanic() {
	if s != nil {
		s.workerPanics.Add(1)
	}
}

func (s *Stats) IncAlertWriteError() {
	if s != nil {
		s.alertWriteErrors.Add(1)
	}
}

func (s *Stats) ObserveMatchDuration(d time.Duration) {
	if s == nil {
		return
	}
	s.matchCount.Add(1)
	s.matchDurationNS.Add(uint64(d))
}

func (s *Stats) ObserveAlerts(alerts []*model.Alert) {
	if s == nil || len(alerts) == 0 {
		return
	}
	s.alertsGenerated.Add(uint64(len(alerts)))
	s.mu.Lock()
	defer s.mu.Unlock()
	for _, alert := range alerts {
		if alert == nil {
			continue
		}
		sev := alert.Severity
		if sev == "" {
			sev = model.SeverityLow
		}
		s.alertsBySeverity[sev]++
	}
}

// Snapshot is a point-in-time view of exported counters.
type Snapshot struct {
	FramesTotal      uint64
	ControlFrames    uint64
	PacketsReceived  uint64
	PacketsProcessed uint64
	DecodeErrors     uint64
	AlertsGenerated  uint64
	MatchCount       uint64
	MatchDurationNS  uint64
	WorkerPanics     uint64
	AlertWriteErrors uint64
	AlertsBySeverity map[model.Severity]uint64
}

func (s *Stats) Snapshot() Snapshot {
	if s == nil {
		return Snapshot{}
	}
	s.mu.RLock()
	defer s.mu.RUnlock()
	bySeverity := make(map[model.Severity]uint64, len(s.alertsBySeverity))
	for sev, count := range s.alertsBySeverity {
		bySeverity[sev] = count
	}
	return Snapshot{
		FramesTotal:      s.framesTotal.Load(),
		ControlFrames:    s.controlFrames.Load(),
		PacketsReceived:  s.packetsReceived.Load(),
		PacketsProcessed: s.packetsProcessed.Load(),
		DecodeErrors:     s.decodeErrors.Load(),
		AlertsGenerated:  s.alertsGenerated.Load(),
		MatchCount:       s.matchCount.Load(),
		MatchDurationNS:  s.matchDurationNS.Load(),
		WorkerPanics:     s.workerPanics.Load(),
		AlertWriteErrors: s.alertWriteErrors.Load(),
		AlertsBySeverity: bySeverity,
	}
}

// RenderPrometheus emits a minimal Prometheus text exposition without adding a
// runtime dependency before the API package is split out.
func RenderPrometheus(snapshot Snapshot, gauges map[string]float64) string {
	var b strings.Builder
	writeCounter(&b, "netsentry_frames_total", "UDS frames received.", snapshot.FramesTotal)
	writeCounter(&b, "netsentry_control_frames_total", "UDS control frames received.", snapshot.ControlFrames)
	writeCounter(&b, "netsentry_packets_received_total", "Packet frames accepted by the receiver.", snapshot.PacketsReceived)
	writeCounter(&b, "netsentry_packets_processed_total", "Packets processed by the pipeline.", snapshot.PacketsProcessed)
	writeCounter(&b, "netsentry_decode_errors_total", "UDS frames rejected during decode or validation.", snapshot.DecodeErrors)
	writeCounter(&b, "netsentry_alerts_generated_total", "Alerts generated by the pipeline.", snapshot.AlertsGenerated)
	writeCounter(&b, "netsentry_rule_match_total", "Rule match operations executed.", snapshot.MatchCount)
	writeCounter(&b, "netsentry_rule_match_duration_seconds_total", "Total time spent matching packets.", float64(snapshot.MatchDurationNS)/float64(time.Second))
	writeCounter(&b, "netsentry_worker_panics_total", "Pipeline worker panics recovered.", snapshot.WorkerPanics)
	writeCounter(&b, "netsentry_alert_write_errors_total", "Alert write failures.", snapshot.AlertWriteErrors)

	severities := make([]string, 0, len(snapshot.AlertsBySeverity))
	for sev := range snapshot.AlertsBySeverity {
		severities = append(severities, string(sev))
	}
	sort.Strings(severities)
	b.WriteString("# HELP netsentry_alerts_by_severity_total Alerts generated by severity.\n")
	b.WriteString("# TYPE netsentry_alerts_by_severity_total counter\n")
	for _, sev := range severities {
		fmt.Fprintf(&b, "netsentry_alerts_by_severity_total{severity=%q} %d\n", sev, snapshot.AlertsBySeverity[model.Severity(sev)])
	}

	names := make([]string, 0, len(gauges))
	for name := range gauges {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		writeGauge(&b, name, gauges[name])
	}
	return b.String()
}

func writeCounter[T ~uint64 | ~float64](b *strings.Builder, name, help string, value T) {
	fmt.Fprintf(b, "# HELP %s %s\n", name, help)
	fmt.Fprintf(b, "# TYPE %s counter\n", name)
	fmt.Fprintf(b, "%s %v\n", name, value)
}

func writeGauge(b *strings.Builder, name string, value float64) {
	fmt.Fprintf(b, "# TYPE %s gauge\n", name)
	fmt.Fprintf(b, "%s %v\n", name, value)
}
